# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"\x80\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"&\n\x08TaskList\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task\"\x07\n\x05\x45mpty2`\n\x0bTaskService\x12)\n\x08GetTasks\x12\x0c.tasks.Empty\x1a\x0f.tasks.TaskList\x12&\n\nCreateTask\x12\x0b.tasks.Task\x1a\x0b.tasks.Taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=23
  _globals['_TASK']._serialized_end=151
  _globals['_TASKLIST']._serialized_start=153
  _globals['_TASKLIST']._serialized_end=191
  _globals['_EMPTY']._serialized_start=193
  _globals['_EMPTY']._serialized_end=200
  _globals['_TASKSERVICE']._serialized_start=202
  _globals['_TASKSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
